name: Release

on:
  push:
    branches:
      - main
    tags:
      - "*"

jobs:
  build:
    name: Publish
    runs-on: ubuntu-18.04
    steps:
      - uses: "actions/checkout@v2.3.2"
        with:
          fetch-depth: 0 # fetch all branches & tags

      - name: "Install Nix ❄️"
        uses: nixbuild/nix-quick-install-action@v2

      - name: "Install Cachix ❄️"
        uses: cachix/cachix-action@v6
        with:
          name: golden
          signingKey: "${{ secrets.CACHIX_SIGNING_KEY }}"

      - name: "Publish ${{ github.ref }} 🚀"
        env:
          PGP_PASSPHRASE: "${{ secrets.PGP_PASSPHRASE }}"
          PGP_SECRET: "${{ secrets.PGP_SECRET }}"
          SONATYPE_PASSWORD: "${{ secrets.SONATYPE_PASSWORD }}"
          SONATYPE_USERNAME: "${{ secrets.SONATYPE_USERNAME }}"
        run: nix-shell --run "sbt ci-release"
