name: sbt-nix-derivation

on:
  push:
    branches:
      - main
    paths:
      - "nix/**"

jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        java:
          - jdk8
          - jdk11
          - jdk14
    steps:
      - uses: actions/checkout@v2.3.2

      - name: "Install Nix ❄️"
        uses: cachix/install-nix-action@v12

      - name: "Install Cachix ❄️"
        uses: cachix/cachix-action@v8
        with:
          name: golden
          signingKey: "${{ secrets.CACHIX_SIGNING_KEY }}"

      - name: "Build sbt derivation with ${{ matrix.java }} 🚀"
        run: nix-build --argstr jdk "${{ matrix.java }}" nix/sbt.nix | cachix push golden
